version: "3.7"

services:
  db:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
